In [1]:
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "fetal_health.csv"

# Load the latest version using the recommended dataset_load
df = kagglehub.dataset_load(
  KaggleDatasetAdapter.PANDAS,
  "andrewmvd/fetal-health-classification",
  file_path
)

print("First 5 records:")
display(df.head())

Using Colab cache for faster access to the 'fetal-health-classification' dataset.
First 5 records:

,baseline value,accelerations,fetal_movement,uterine_contractions,light_decelerations,severe_decelerations,prolongued_decelerations,abnormal_short_term_variability,mean_value_of_short_term_variability,percentage_of_time_with_abnormal_long_term_variability,...,histogram_min,histogram_max,histogram_number_of_peaks,histogram_number_of_zeroes,histogram_mode,histogram_mean,histogram_median,histogram_variance,histogram_tendency,fetal_health
0,120.0,0.000,0.0,0.000,0.000,0.0,0.0,73.0,0.5,43.0,...,62.0,126.0,2.0,0.0,120.0,137.0,121.0,73.0,1.0,2.0
1,132.0,0.006,0.0,0.006,0.003,0.0,0.0,17.0,2.1,0.0,...,68.0,198.0,6.0,1.0,141.0,136.0,140.0,12.0,0.0,1.0
2,133.0,0.003,0.0,0.008,0.003,0.0,0.0,16.0,2.1,0.0,...,68.0,198.0,5.0,1.0,141.0,135.0,138.0,13.0,0.0,1.0
3,134.0,0.003,0.0,0.008,0.003,0.0,0.0,16.0,2.4,0.0,...,53.0,170.0,11.0,0.0,137.0,134.0,137.0,13.0,1.0,1.0
4,132.0,0.007,0.0,0.008,0.000,0.0,0.0,16.0,2.4,0.0,...,53.0,170.0,9.0,0.0,137.0,136.0,138.0,11.0,1.0,1.0

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Data setup
X = df.drop(columns=['fetal_health'])
y = df['fetal_health']

# Split the dataset into training (80%) and testing (20%) sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

gb_model = GradientBoostingClassifier(random_state=42)
gb_model.fit(X_train, y_train)

y_pred = gb_model.predict(X_test)

# Evaluate the model performance
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.4f}\n")
print("Classification Report:")
print(classification_report(y_test, y_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.9296

Classification Report:
              precision    recall  f1-score   support

         1.0       0.95      0.97      0.96       332
         2.0       0.85      0.69      0.77        59
         3.0       0.84      0.91      0.88        35

    accuracy                           0.93       426
   macro avg       0.88      0.86      0.87       426
weighted avg       0.93      0.93      0.93       426

Confusion Matrix:
[[323   6   3]
 [ 15  41   3]
 [  2   1  32]]

In [3]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)
y_pred = rf_model.predict(X_test)

# Evaluation
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.4f}\n")
print("Classification Report:")
print(classification_report(y_test, y_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.9249

Classification Report:
              precision    recall  f1-score   support

         1.0       0.94      0.98      0.96       332
         2.0       0.83      0.68      0.75        59
         3.0       0.85      0.83      0.84        35

    accuracy                           0.92       426
   macro avg       0.88      0.83      0.85       426
weighted avg       0.92      0.92      0.92       426

Confusion Matrix:
[[325   5   2]
 [ 16  40   3]
 [  3   3  29]]

In [4]:
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train_scaled, y_train)
y_pred = knn.predict(X_test_scaled)

# Evaluation
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.4f}\n")
print("Classification Report:")
print(classification_report(y_test, y_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.8709

Classification Report:
              precision    recall  f1-score   support

         1.0       0.90      0.96      0.93       332
         2.0       0.61      0.47      0.53        59
         3.0       0.88      0.66      0.75        35

    accuracy                           0.87       426
   macro avg       0.80      0.70      0.74       426
weighted avg       0.86      0.87      0.86       426

Confusion Matrix:
[[320  11   1]
 [ 29  28   2]
 [  5   7  23]]

In [5]:
from lightgbm import LGBMClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Initialize LightGBM Classifier
lgb_model = LGBMClassifier(random_state=42, verbose=-1)

# Train the model
lgb_model.fit(X_train, y_train)

# Predict on the test set
y_pred_lgb = lgb_model.predict(X_test)

# Evaluate performance
accuracy = accuracy_score(y_test, y_pred_lgb)
print(f"Accuracy: {accuracy:.4f}\n")
print("Classification Report:")
print(classification_report(y_test, y_pred_lgb))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_lgb))

Accuracy: 0.9437

Classification Report:
              precision    recall  f1-score   support

         1.0       0.96      0.98      0.97       332
         2.0       0.88      0.75      0.81        59
         3.0       0.89      0.91      0.90        35

    accuracy                           0.94       426
   macro avg       0.91      0.88      0.89       426
weighted avg       0.94      0.94      0.94       426

Confusion Matrix:
[[326   5   1]
 [ 12  44   3]
 [  2   1  32]]

In [6]:
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# XGBoost expects 0-indexed integer labels: [0, 1, 2] instead of [1.0, 2.0, 3.0]
y_train_xgb = (y_train - 1).astype(int)
y_test_xgb = (y_test - 1).astype(int)

# Initialize the XGBoost Classifier
xgb_model = XGBClassifier(random_state=42, use_label_encoder=False, eval_metric='mlogloss')

# Train the model
xgb_model.fit(X_train, y_train_xgb)

# Predict on the test set
y_pred_xgb_raw = xgb_model.predict(X_test)

# Map predictions back to the original classes [1.0, 2.0, 3.0]
y_pred_xgb = y_pred_xgb_raw + 1

# Evaluate performance
accuracy = accuracy_score(y_test, y_pred_xgb)
print(f"Accuracy: {accuracy:.4f}\n")
print("Classification Report:")
print(classification_report(y_test, y_pred_xgb))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_xgb))

/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [03:02:51] WARNING: /__w/xgboost/xgboost/src/learner.cc:794:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

Accuracy: 0.9390

Classification Report:
              precision    recall  f1-score   support

         1.0       0.96      0.97      0.97       332
         2.0       0.83      0.76      0.80        59
         3.0       0.91      0.91      0.91        35

    accuracy                           0.94       426
   macro avg       0.90      0.88      0.89       426
weighted avg       0.94      0.94      0.94       426

Confusion Matrix:
[[323   8   1]
 [ 12  45   2]
 [  2   1  32]]

In [7]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train, y_train)
y_pred_dt = dt_model.predict(X_test)

# Evaluate performance
accuracy = accuracy_score(y_test, y_pred_dt)
print(f"Accuracy: {accuracy:.4f}\n")
print("Classification Report:")
print(classification_report(y_test, y_pred_dt))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_dt))

Accuracy: 0.9014

Classification Report:
              precision    recall  f1-score   support

         1.0       0.94      0.95      0.95       332
         2.0       0.73      0.64      0.68        59
         3.0       0.81      0.83      0.82        35

    accuracy                           0.90       426
   macro avg       0.82      0.81      0.82       426
weighted avg       0.90      0.90      0.90       426

Confusion Matrix:
[[317  13   2]
 [ 16  38   5]
 [  5   1  29]]

In [8]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Initialize the Support Vector Classifier
# Using RBF kernel as a strong default
svm_model = SVC(kernel='rbf', random_state=42)

# Train the model on the scaled data
svm_model.fit(X_train_scaled, y_train)

# Predict on the scaled test set
y_pred_svm = svm_model.predict(X_test_scaled)

# Evaluate performance
accuracy = accuracy_score(y_test, y_pred_svm)
print(f"Accuracy: {accuracy:.4f}\n")
print("Classification Report:")
print(classification_report(y_test, y_pred_svm))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_svm))

Accuracy: 0.8944

Classification Report:
              precision    recall  f1-score   support

         1.0       0.93      0.97      0.95       332
         2.0       0.67      0.58      0.62        59
         3.0       0.86      0.71      0.78        35

    accuracy                           0.89       426
   macro avg       0.82      0.75      0.78       426
weighted avg       0.89      0.89      0.89       426

Confusion Matrix:
[[322   8   2]
 [ 23  34   2]
 [  1   9  25]]

In [9]:
import pandas as pd
from lightgbm import LGBMClassifier
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier
from sklearn.metrics import make_scorer, recall_score
from sklearn.model_selection import RepeatedStratifiedKFold, cross_validate
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier

try:
    from catboost import CatBoostClassifier
    has_catboost = True
except ImportError:
    has_catboost = False

y_cv = (y_train - 1).astype(int)

models = {
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "Random Forest": RandomForestClassifier(n_estimators=300, random_state=42),
    "k-NN (scaled)": make_pipeline(StandardScaler(), KNeighborsClassifier(n_neighbors=5)),
    "Gradient Boosting": GradientBoostingClassifier(random_state=42),
    "LightGBM": LGBMClassifier(random_state=42, verbose=-1),
    "XGBoost": XGBClassifier(random_state=42, eval_metric="mlogloss"),
    "SVM (scaled)": make_pipeline(StandardScaler(), SVC(kernel='rbf', random_state=42))
}

if has_catboost:
    models["Catboost"] = CatBoostClassifier(random_state=42, verbose=0)

scoring = {
    "accuracy": "accuracy",
    "macro_f1": "f1_macro",
    "recall_normal": make_scorer(recall_score, labels=[0], average="macro"),
    "recall_suspect": make_scorer(recall_score, labels=[1], average="macro"),
    "recall_pathological": make_scorer(recall_score, labels=[2], average="macro"),
}

cv = RepeatedStratifiedKFold(n_splits=5, n_repeats=3, random_state=42)

rows = []
for name, model in models.items():
    res = cross_validate(model, X_train, y_cv, cv=cv, scoring=scoring, n_jobs=-1)
    row = {"Model": name}
    for metric in scoring:
        scores = res[f"test_{metric}"]
        row[metric] = f"{scores.mean():.3f} ± {scores.std():.3f}"
    rows.append(row)

results = pd.DataFrame(rows).set_index("Model")
display(results.sort_values("macro_f1", ascending=False))

,accuracy,macro_f1,recall_normal,recall_suspect,recall_pathological
Model,,,,,
XGBoost,0.955 ± 0.007,0.920 ± 0.015,0.983 ± 0.006,0.804 ± 0.046,0.936 ± 0.035
LightGBM,0.954 ± 0.005,0.920 ± 0.011,0.984 ± 0.006,0.804 ± 0.032,0.931 ± 0.046
Gradient Boosting,0.953 ± 0.007,0.917 ± 0.014,0.982 ± 0.007,0.815 ± 0.031,0.912 ± 0.043
Random Forest,0.942 ± 0.005,0.894 ± 0.017,0.981 ± 0.009,0.763 ± 0.039,0.877 ± 0.061
Decision Tree,0.922 ± 0.017,0.874 ± 0.025,0.956 ± 0.015,0.736 ± 0.062,0.917 ± 0.053
SVM (scaled),0.910 ± 0.014,0.831 ± 0.026,0.972 ± 0.011,0.650 ± 0.049,0.766 ± 0.043
k-NN (scaled),0.904 ± 0.014,0.820 ± 0.025,0.970 ± 0.008,0.629 ± 0.071,0.749 ± 0.045

In [10]:
import pandas as pd
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from sklearn.ensemble import (
    RandomForestClassifier,
    VotingClassifier,
    StackingClassifier,
    GradientBoostingClassifier
)
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import make_scorer, recall_score
from sklearn.model_selection import RepeatedStratifiedKFold, cross_validate
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC

y_cv = (y_train - 1).astype(int)

base = [
    ("rf", RandomForestClassifier(n_estimators=300, random_state=42)),
    ("lgb", LGBMClassifier(random_state=42, verbose=-1)),
    ("xgb", XGBClassifier(random_state=42, eval_metric="mlogloss")),
    ("svm", make_pipeline(StandardScaler(), SVC(probability=True, random_state=42))),
]

models = {
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "Random Forest": RandomForestClassifier(n_estimators=300, random_state=42),
    "k-NN (scaled)": make_pipeline(StandardScaler(), KNeighborsClassifier(n_neighbors=5)),
    "Gradient Boosting": GradientBoostingClassifier(random_state=42),
    "LightGBM": LGBMClassifier(random_state=42, verbose=-1, class_weight='balanced'),
    "XGBoost": XGBClassifier(random_state=42, eval_metric="mlogloss"),
    "Soft Voting": VotingClassifier(base, voting="soft"),
    "Stacking": StackingClassifier(
        base,
        final_estimator=LogisticRegression(max_iter=1000),
        cv=3,
        n_jobs=-1,
    ),
}

scoring = {
    "accuracy": "accuracy",
    "macro_f1": "f1_macro",
    "recall_normal": make_scorer(recall_score, labels=[0], average="macro"),
    "recall_suspect": make_scorer(recall_score, labels=[1], average="macro"),
    "recall_pathological": make_scorer(recall_score, labels=[2], average="macro"),
}

cv = RepeatedStratifiedKFold(n_splits=5, n_repeats=3, random_state=42)

rows = []
for name, model in models.items():
    print(f"Running {name}...", flush=True)
    res = cross_validate(model, X_train, y_cv, cv=cv, scoring=scoring, n_jobs=1)
    row = {"Model": name}
    for metric in scoring:
        scores = res[f"test_{metric}"]
        row[metric] = f"{scores.mean():.3f} ± {scores.std():.3f}"
    rows.append(row)
    print(f"  done -> macro_f1 = {row['macro_f1']}", flush=True)

results = pd.DataFrame(rows).set_index("Model")
display(results.sort_values("macro_f1", ascending=False))

Running Decision Tree...
  done -> macro_f1 = 0.874 ± 0.025
Running Random Forest...
  done -> macro_f1 = 0.894 ± 0.017
Running k-NN (scaled)...
  done -> macro_f1 = 0.820 ± 0.025
Running Gradient Boosting...
  done -> macro_f1 = 0.917 ± 0.014
Running LightGBM...
  done -> macro_f1 = 0.918 ± 0.009
Running XGBoost...
  done -> macro_f1 = 0.920 ± 0.015
Running Soft Voting...
  done -> macro_f1 = 0.918 ± 0.012
Running Stacking...
  done -> macro_f1 = 0.920 ± 0.012

,accuracy,macro_f1,recall_normal,recall_suspect,recall_pathological
Model,,,,,
XGBoost,0.955 ± 0.007,0.920 ± 0.015,0.983 ± 0.006,0.804 ± 0.046,0.936 ± 0.035
Stacking,0.953 ± 0.006,0.920 ± 0.012,0.981 ± 0.006,0.807 ± 0.047,0.941 ± 0.036
Soft Voting,0.953 ± 0.005,0.918 ± 0.012,0.983 ± 0.006,0.795 ± 0.039,0.936 ± 0.037
LightGBM,0.953 ± 0.006,0.918 ± 0.009,0.977 ± 0.007,0.835 ± 0.034,0.934 ± 0.028
Gradient Boosting,0.953 ± 0.007,0.917 ± 0.014,0.982 ± 0.007,0.815 ± 0.031,0.912 ± 0.043
Random Forest,0.942 ± 0.005,0.894 ± 0.017,0.981 ± 0.009,0.763 ± 0.039,0.877 ± 0.061
Decision Tree,0.922 ± 0.017,0.874 ± 0.025,0.956 ± 0.015,0.736 ± 0.062,0.917 ± 0.053
k-NN (scaled),0.904 ± 0.014,0.820 ± 0.025,0.970 ± 0.008,0.629 ± 0.071,0.749 ± 0.045

In [11]:
from sklearn.utils.class_weight import compute_sample_weight

w = compute_sample_weight("balanced", y_cv)

xgb_bal = XGBClassifier(random_state=42, eval_metric="mlogloss")

res = cross_validate(
    xgb_bal, X_train, y_cv, cv=cv, scoring=scoring,
    n_jobs=-1, params={"sample_weight": w},   # use fit_params= on sklearn < 1.4
)

row = {"Model": "XGBoost balanced"}
for metric in scoring:
    s = res[f"test_{metric}"]
    row[metric] = f"{s.mean():.3f} ± {s.std():.3f}"
display(pd.DataFrame([row]).set_index("Model"))

,accuracy,macro_f1,recall_normal,recall_suspect,recall_pathological
Model,,,,,
XGBoost balanced,0.952 ± 0.007,0.919 ± 0.010,0.972 ± 0.010,0.842 ± 0.030,0.953 ± 0.025

In [12]:
from sklearn.model_selection import GridSearchCV, StratifiedKFold
from sklearn.utils.class_weight import compute_sample_weight
from xgboost import XGBClassifier
import pandas as pd

y_cv = (y_train - 1).astype(int)
w = compute_sample_weight("balanced", y_cv)

param_grid = {
    "max_depth": [3, 5, 7],
    "learning_rate": [0.03, 0.1],
    "n_estimators": [200, 400],
    "subsample": [0.8, 1.0],
    "colsample_bytree": [0.7, 1.0],
    "min_child_weight": [1, 3],
}

grid = GridSearchCV(
    XGBClassifier(random_state=42, eval_metric="mlogloss"),
    param_grid,
    scoring="f1_macro",
    cv=StratifiedKFold(n_splits=5, shuffle=True, random_state=42),
    n_jobs=-1,
    verbose=1,
)
grid.fit(X_train, y_cv, sample_weight=w)

print("Best params:", grid.best_params_)
print(f"Best CV macro F1: {grid.best_score_:.4f}")

res = pd.DataFrame(grid.cv_results_)
cols = ["mean_test_score", "std_test_score"] + [f"param_{p}" for p in param_grid]
display(res.sort_values("mean_test_score", ascending=False)[cols].head(5))

Fitting 5 folds for each of 96 candidates, totalling 480 fits
Best params: {'colsample_bytree': 1.0, 'learning_rate': 0.03, 'max_depth': 7, 'min_child_weight': 1, 'n_estimators': 200, 'subsample': 0.8}
Best CV macro F1: 0.9268

,mean_test_score,std_test_score,param_max_depth,param_learning_rate,param_n_estimators,param_subsample,param_colsample_bytree,param_min_child_weight
64,0.926835,0.003990,7,0.03,200,0.8,1.0,1
66,0.925987,0.007724,7,0.03,400,0.8,1.0,1
19,0.925844,0.004993,7,0.03,400,1.0,0.7,1
35,0.925818,0.008459,5,0.10,400,1.0,0.7,1
33,0.924971,0.006531,5,0.10,200,1.0,0.7,1

In [13]:
best_xgb = XGBClassifier(random_state=42, eval_metric="mlogloss", **grid.best_params_)

res = cross_validate(
    best_xgb, X_train, y_cv, cv=cv, scoring=scoring,
    n_jobs=-1, params={"sample_weight": w},   # fit_params= on sklearn < 1.4
)

row = {"Model": "XGBoost balanced + grid"}
for metric in scoring:
    s = res[f"test_{metric}"]
    row[metric] = f"{s.mean():.3f} ± {s.std():.3f}"
display(pd.DataFrame([row]).set_index("Model"))

,accuracy,macro_f1,recall_normal,recall_suspect,recall_pathological
Model,,,,,
XGBoost balanced + grid,0.951 ± 0.006,0.919 ± 0.010,0.965 ± 0.008,0.871 ± 0.033,0.953 ± 0.031

In [14]:
import joblib

# Fit on the full training set, with the same balanced weights used in CV
best_xgb.fit(X_train, y_cv, sample_weight=w)

# Save
joblib.dump(best_xgb, "xgb_fetal_health.joblib")

['xgb_fetal_health.joblib']